# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a063f80ff18de0cd8b33bf5d2f9f66c87852d017e37ba7e4abeaab9e592188181bacf74a98a1ebec06e8798b57fbe6da81b3718e5c904e96eeaa74fe58596ee6

test:
  secret_key_base: c3a7492195dc45f324609b4b6e2418c3054b6aa8a91cec3641aeb3d85bc4376129428122b621063051c6d0990aeff2c914fc1e3b0986d51d673336440eb3c4e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
